### ISSUE TITLE
how to preprocess the amazon book data?

### ISSUE THREAD

**Issue by Cloudcatcher888** [THUDM/ComiRec#1]

**Comment by cenyk1230** [comment]
Hi @Cloudcatcher888,

Thank you for your attention to our work. 

I add the preprocessing code in the `preprocess/` directory. You should first download the original data from http://jmcauley.ucsd.edu/data/amazon/index.html, and then run `python preprocess/data.py` to preprocess the Amazon Book dataset. If you want to compute the diversity in the experiment, you also need to run `python preprocess/category.py` to generate the corresponding category information.
