### ISSUE TITLE
关于item编码的问题

### ISSUE THREAD

**Issue by Aliang-CN** [THUDM/ComiRec#10]
@cenyk1230 
您好！有个小细节的问题想咨询一下你，这个item的编码是从1开始的吗？
https://github.com/THUDM/ComiRec/blob/master/preprocess/data.py#L57
这么做的主要目的是什么呢

**Comment by cenyk1230** [comment]
Hi @Aliang-CN,

我把0留出来作为padding的标号了。

**Comment by Aliang-CN** [comment]
> Hi @Aliang-CN,
> 
> 我把0留出来作为padding的标号了。

哦哦，我想起来了，在算mask的确有这一步。还有一个细节问题，那最后这个item_count 是不是也要加1?
https://github.com/THUDM/ComiRec/blob/master/src/train.py#L352

**Comment by cenyk1230** [comment]
@Aliang-CN 是的，要比实际item数量多1。

**Comment by ucasiggcas** [comment]
在book_item_cate.txt中最小的cate是1，在book_train.txt中最小的是1，那么请问需要对代码进行调整吗？还是说代码已经考虑到这点了？多谢大佬
