### ISSUE TITLE
关于代码中NDCG@N计算方式的问题

### ISSUE THREAD

**Issue by lazy2panda** [THUDM/ComiRec#21]
论文中的NDCG@N如下：
![image](https://user-images.githubusercontent.com/7948261/126248754-2c62c686-cf75-4d41-ac6f-0cf52024ff35.png)
代码中的ndcg计算方式如下：
dcg：https://github.com/THUDM/ComiRec/blob/master/src/train.py#L143
idcg：https://github.com/THUDM/ComiRec/blob/master/src/train.py#L148
论文中的dcg求和项分母是k，是指给用户u推荐的第k个item。
论文中的k是否对应dcg计算代码中的no？
我理解no是用户实际交互项中的编号，并不是给用户推荐的第k个item。

请问这里应该怎么理解？谢谢

**Comment by cenyk1230** [comment]
Hi @lazy2panda , 原始代码里的ndcg计算确实跟论文里不一致，可以参见issue #6 。dev分支对ndcg计算进行了修复。

**Comment by lazy2panda** [comment]
好的，感谢~
