### ISSUE TITLE
关于model.py中class Model_DNN的一个问题

### ISSUE THREAD

**Issue by codefish1990** [THUDM/ComiRec#4]
Model_DNN实现中：
masks = tf.concat([tf.expand_dims(self.mask, -1) for _ in range(hidden_size)], axis=-1)是否应该改成
masks = tf.concat([tf.expand_dims(self.mask, -1) for _ in range(embedding_dim)], axis=-1)?

**Comment by cenyk1230** [comment]
@codefish1990,

Thank you for pointing it out. It really should be `embedding_dim` instead of `hidden_size`. In our experiments, we set the same value for these two hyper-parameters, and thus I didn't find this mistake before.
