### ISSUE TITLE
questions about computing ndcg score

### ISSUE THREAD

**Issue by zhuojw10** [THUDM/ComiRec#6]
The NDCG score computed in L91~L94 seems contradicted with the definition in the paper: dcg is computed according to item in the ground truth with the k-th nearest time instead of the k-th recommended item as mentioned in Eq. (16) of the paper.
Is it correct?

**Comment by cenyk1230** [comment]
Hi @zhuojw10,

Thank you for pointing it out. It seems that the `iid_list` and `item_list` should be swapped in L91 and L92. I will double-check the calculation of the NDCG score.

**Comment by cenyk1230** [comment]
Hi @zhuojw10,

I have updated the computation of the NDCG score and have pushed it to the dev branch. Could you please help to check the implementation? 
(This is the modification: https://github.com/THUDM/ComiRec/commit/a3489dfeea9539c440f614b4643e6887c38fb61e)

**Comment by zhuojw10** [comment]
@cenyk1230 Thanks for your update~ I think the current version is currect.
