### ISSUE TITLE
关于停止梯度更新的问题

### ISSUE THREAD

**Issue by Aliang-CN** [THUDM/ComiRec#7]
作者：
     您好！非常感谢您的开源工作，对于源码，我有一个小问题，在胶囊网络里面这个停止梯度更新是起什么作用呢？
@cenyk1230 

https://github.com/THUDM/ComiRec/blob/8303ab48e9c2bf6719b9771ab78e41d72e87cfcd/src/model.py#L139

**Comment by cenyk1230** [comment]
Hi @Aliang-CN,

Thank you for your interest in our work. As we know, there is an iterative process to compute the weights between capsules. The `stop_gradient` will stop the backward propagation gradient from capsule weights to item embedding.

**Comment by Aliang-CN** [comment]
还有一个问题想请教你，数据集上的第三列应该是seq index，这个排序是怎么样的。0是最近还是最早呢？

**Comment by cenyk1230** [comment]
Hi @Aliang-CN, 

0是最早。

**Comment by Aliang-CN** [comment]
> Hi @Aliang-CN,
> 
> 0是最早。

您好，非常感谢您的回答。我后来通过数据预处理得知0是最早的。我在我生产上跑您的算法，线下表现很亮眼，recall能达到50的表现，让我很吃惊。

**Comment by cenyk1230** [comment]
感谢你的尝试！
