### ISSUE TITLE
GRU4Rec  book数据集，没有论文中的recall高

### ISSUE THREAD

**Issue by zhangqianjin** [THUDM/ComiRec#8]
请问你的论文中GRU4Rec的参数设置是？我使用的Adam的优化器，测试了lr=0.005和0.001，topN 为50，我的recall才0.35左右

**Comment by cenyk1230** [comment]
Hi @zhangqianjin,

还请麻烦提供一下你训练过程中tensorboard的截图。

**Comment by zhangqianjin** [comment]
> Hi @zhangqianjin,
> 
> 还请麻烦提供一下你训练过程中tensorboard的截图。

运行了你的代码，和论文上一致，我是用pytorch改写的，正在查原因
