### ISSUE TITLE
puzzle at user_id in training and serving

### ISSUE THREAD

**Issue by TiffinyHu** [THUDM/ComiRec#9]
Thanks for providing the code!!
user_id is transformed into index in train、test and evaluation, so the model can predict for user whose user_id exists in  train, how about other users not exist in train?
I'm very puzzled about how to handle user_id feature in recommendation

**Comment by cenyk1230** [comment]
Hi @TiffinyHu,

Thank you for your attention to our work. Actually, the user_id is not used in our code. We only use historical items to predict the current item.
